permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
input: GFM

# 作者信息
author: 
name: Aurthur
email: aurthurxlc@gmail.com
link: http://blog.gitos.cn
github: http://github.com/Aurthur-LK

# 站点信息
title: Aurthur's Blog 
description: Aurthur's Blog
url: http://blog.gitos.cn
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://7vzn66.com1.z0.glb.clouddn.com/blog.png
favicon: http://7vzn66.com1.z0.glb.clouddn.com/blog.ico

# google analytics 设置
#ga:
 # id: 
  #url: 

# disqus 设置
#disqus:
 # shortname: aurthur-zh
